const fs=require('fs'),vm=require('vm'),assert=require('node:assert/strict');
const {JSDOM}=require(process.env.VENUE_JSDOM||'jsdom');
const root=__dirname+'/../',html=fs.readFileSync(root+'index.html','utf8');
const dom=new JSDOM(html.replace(/<script[\s\S]*?<\/script>/g,''),{url:'https://example.invalid',runScripts:'outside-only'});
const w=dom.window,context=dom.getInternalVMContext(),run=s=>vm.runInContext(s,context);
w.__TEST__=true;w.confirm=()=>true;w.HTMLElement.prototype.scrollIntoView=function(){};
w.HTMLDialogElement.prototype.showModal=function(){this.open=true};w.HTMLDialogElement.prototype.close=function(){this.open=false};
run(html.match(/<script>([\s\S]*?)<\/script>/)[1]);
for(const file of ['live.js','recurring.js','booking-ui.js','booking-flow.js','assistant-ui.js','member-tools.js'])run(fs.readFileSync(root+file,'utf8'));
const field=(form,name)=>w.document.getElementById(form).elements[name];
(async()=>{
 run("session={user:{id:'u1'}};liveReady=true;me='Account owner';rooms=[{id:1,name:'Room One',enabled:true},{id:2,name:'Room Two',enabled:true}];bookings=[];selected=addDays(dayKey(),10);month=selected.slice(0,7);bookingProfile={name:'Default PIC',fellowship:'乐龄团契',contact:'123'};render();openForm(1)");
 assert.equal(field('booking-form','pic').value,'Default PIC');assert.equal(field('booking-form','group').value,'乐龄团契');assert.equal(field('booking-form','contact').value,'123');
 field('booking-form','pic').value='Other person';field('booking-form','pic').dispatchEvent(new w.Event('input',{bubbles:true}));
 assert.equal(field('booking-form','contact').value,'');assert.equal(run('bookingProfile.name'),'Default PIC');
 run('bookForOther()');assert.equal(field('booking-form','pic').value,'');assert.equal(field('booking-form','contact').value,'');
 run('openProfile()');assert.equal(field('profile-form','name').value,'Default PIC');assert(!field('profile-form','fellowship_choice').required);
 let rpcCalls=[];w.rpcCalls=rpcCalls;
 run("db={rpc:async(name,args)=>{rpcCalls.push({name,...args});return {data:args.payload,error:null}}}");
 field('profile-form','name').value='Saved name';
 await run("saveProfile({preventDefault(){},target:document.getElementById('profile-form')})");
 assert.equal(rpcCalls[0].name,'venue_profile');assert.equal(run('bookingProfile.name'),'Saved name');
 run("bookings=[{id:'00000000-0000-0000-0000-000000000001',series_id:'s1',owner:'member',room:1,date:selected,start:'09:00',end:'10:00',title:'Study',group:'青团',pic:'PIC',contact:'999',notes:'',status:'confirmed',history:[],created:Date.now(),booked_by:'Account owner'}];openForm(null,bookings[0].id)");
 assert(w.document.getElementById('occurrence-form'));assert(!field('occurrence-form','change_room').checked);
 run("openOccurrenceEditor(bookings[0].id,'future')");
 assert(!field('occurrence-form','value_date'));
 field('occurrence-form','change_pic').checked=true;run("toggleOccurrenceField(document.getElementById('occurrence-form'),'pic')");
 assert.equal(field('occurrence-form','value_contact').value,'');assert(field('occurrence-form','change_contact').checked);
 field('occurrence-form','value_pic').value='Another PIC';
 const patch=run("occurrencePayload(document.getElementById('occurrence-form')).patch");
 assert.equal(patch.pic,'Another PIC');assert.equal(patch.contact,'');assert(!Object.hasOwn(patch,'room'));
 run("db.rpc=async(name,args)=>{rpcCalls.push({name,...args});return {data:[{id:bookings[0].id,version:'v1',date:selected,new_date:selected,room:1,start:'09:00',end:'10:00',available:true,exception:true,reapproval:false}],error:null}}");
 await run("previewOccurrence({preventDefault(){},target:document.getElementById('occurrence-form')})");
 assert(!field('occurrence-form','edit_id').checked);assert(w.document.getElementById('occurrence-confirm').disabled);
 field('occurrence-form','edit_id').checked=true;run('updateOccurrenceSelection()');
 assert(w.document.getElementById('occurrence-confirm').textContent.includes('(1)'));
 run("db.rpc=async(name,args)=>{rpcCalls.push({name,...args});return {data:{count:1},error:null}};refreshLive=async()=>{}");
 await run('confirmOccurrence()');
 const last=rpcCalls.at(-1);assert.equal(last.action,'apply');assert.equal(last.payload.ids.length,1);assert.equal(last.payload.versions[last.payload.ids[0]],'v1');
 run("openAssistant();assistantDraft={room:1,date:selected,start:'09:00',end:'10:00',purpose:'Study',fellowship:'Explicit group',pic:'',frequency:'once',weekdays:[],monthly:'date'};bookingProfile={name:'Default PIC',fellowship:'Default group',contact:'123'};let captured='';assistantAnswer=s=>captured=s;assistantUseDefaults()");
 assert.equal(run('captured'),'PIC: Default PIC');
 run("document.getElementById('assistant-result').innerHTML=assistantSummary({draft:assistantDraft,availability:{kind:'single',available:true}});assistantOtherPerson()");
 assert.equal(run('assistantOnBehalf'),true);assert(!w.document.getElementById('assistant-result').innerHTML.includes('onclick="assistantUseDefaults()"'));
 run("assistantDraft.pic='Default PIC';useAssistantDraft()");
 assert.equal(field('booking-form','contact').value,'');assert.equal(field('booking-form','group').value,'Explicit group');
 run("openMyRecurring()");assert(w.document.getElementById('modal').textContent.includes('Study'));
 run("chooseRecurringAction(bookings[0].id)");assert(w.document.getElementById('modal').textContent.includes('This and future dates'));
 run("openSeries('s1')");assert(!w.document.getElementById('modal').textContent.includes('Confirmed dates need an admin'));
 run("clearAccountState()");assert.equal(Object.keys(run('bookingProfile')).length,0);
 console.log('PASS: real DOM profile/autofill, on-behalf contact clearing, sparse bulk edits, exception opt-in, snapshot submission, assistant defaults and recurring entry points, account reset.');
 dom.window.close();
})().catch(e=>{console.error(e);dom.window.close();process.exitCode=1});
